package HelloApp;


/**
* HelloApp/hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Saturday, April 10, 2021 5:13:42 PM CST
*/

public interface hello extends helloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface hello
