package HelloApp;

/**
* HelloApp/helloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Saturday, April 10, 2021 5:13:42 PM CST
*/

public final class helloHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.hello value = null;

  public helloHolder ()
  {
  }

  public helloHolder (HelloApp.hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.helloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.helloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.helloHelper.type ();
  }

}
