package HelloApp;


/**
* HelloApp/helloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Saturday, April 10, 2021 5:13:43 PM CST
*/

public interface helloOperations 
{
  String sayHello ();
  boolean isEven (int value);
} // interface helloOperations
